export const GET_FEEDS_START = 'GET_FEEDS_START';
export const GET_FEEDS_FAILED = 'GET_FEEDS_FAILED';
export const GET_FEEDS_SUCCESS = 'GET_FEEDS_SUCCESS';


export const ADD_FEED_START = 'ADD_FEED_START';
export const ADD_FEED_FAILED = 'ADD_FEED_FAILED';
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';

export const UPDATE_COUNTERS = 'UPDATE_COUNTERS';


export const REMOVE_FEED_START = 'REMOVE_FEED_START';
export const REMOVE_FEED_FAILED = 'REMOVE_FEED_FAILED';
export const REMOVE_FEED_SUCCESS = 'REMOVE_FEED_SUCCESS';