export const GET_FRIENDS_START = 'GET_FRIENDS_START';
export const GET_FRIENDS_FAILED = 'GET_FRIENDS_FAILED';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';

export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
