export const ADD_LIKE_DISLIKE = 'ADD_LIKE_DISLIKE';
export const REMOVE_LIKE_DISLIKE = 'ADD_LIKE_DISLIKE';
export const CHANGE_LIKE_DISLIKE = 'ADD_LIKE_DISLIKE';

export const LIKE_DISLIKE_STARTED = 'LIKE_DISLIKE_STARTED';
export const LIKE_DISLIKE_SUCCESS = 'LIKE_DISLIKE_SUCCESS';
export const LIKE_DISLIKE_FAILED = 'LIKE_DISLIKE_FAILED';


export const GET_LIKE_STARTED = 'GET_LIKE_STARTED';
export const GET_LIKE_FAILED = 'GET_LIKE_FAILED';
export const GET_LIKE_SUCCESS = 'GET_LIKE_SUCCESS';

export const REUPDATE_LIKES = 'REUPDATE_LIKES';