export const LIKE_PRESS_STARTED = 'LIKE_PRESS_STARTED';
export const LIKE_PRESS_FAILED = 'LIKE_PRESS_FAILED';
export const LIKE_PRES_SUCCESS = 'LIKE_PRES_SUCCESS';

export const DISLIKE_PRESS_STARTED = 'DISLIKE_PRESS_STARTED';
export const DISLIKE_PRESS_FAILED = 'DISLIKE_PRESS_FAILED';
export const DISLIKE_PRES_SUCCESS = 'DISLIKE_PRES_SUCCESS';

export const GET_LIKE_STARTED = 'GET_LIKE_STARTED';
export const GET_LIKE_FAILED = 'GET_LIKE_FAILED';
export const GET_LIKE_SUCCESS = 'GET_LIKE_SUCCESS';